export const PROP_KEY_JOY_CONFIG_SET_VALUE = `__joy_config_set_value`;
export const SYMPH_CONFIG_LOADERS = `__SYMPH_CONFIG_LOADERS`;

export const SYMPH_CONFIG_DEFAULT_VALUE = `SYMPH_CONFIG_DEFAULT_VALUE`;
export const SYMPH_CONFIG_INIT_VALUE = `SYMPH_CONFIG_INIT_VALUE`;
export const SYMPH_CONFIG_OPTIONS = `SYMPH_CONFIG_OPTIONS`;
